org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=fluidlogistics
mod_name=Create FluidLogistics 
mod_license=All rights reserved.
mod_version=1.2.7
mod_group_id=com.yision.fluidlogistics
mod_authors=Yision
mod_description=Fluid logistics extension for Create mod.

#依赖相关
create_minecraft_version=1.20.1
flywheel_minecraft_version=1.20.1
create_version=6.0.8-289
create_version_range=[6.0.8,6.0.9)
ponder_version=1.0.91
flywheel_version=1.0.5
registrate_version=MC1.20-1.3.3
mixin_extras_version=0.5.0
jei_minecraft_version=1.20.1
jei_version=15.20.0.106
jade_id=4973483
emi_version=1.1.22+1.20.1
kaleidoscope_tavern_version=mUnU2u9e
kaleidoscope_tavern_version_range=[1.2.0,)
