modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"

[[mods]] 
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}" 
displayURL="https://modrinth.com/mod/createfluidlogistic"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="fluidlogistics.mixins.json"

[[dependencies.${mod_id}]] 
    modId="neoforge" 
    type="required" 
    versionRange="[${neo_version},)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[19.0.0,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="emi"
    type="optional"
    versionRange="[1.1.22,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[15.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_enchantment_industry"
    type="optional"
    versionRange="[2.3.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create_dragons_plus"
    type="optional"
    versionRange="[1.10.0,)"
    ordering="AFTER"
    side="BOTH"
